image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-authentication-microservice:
  stage: build
  script:
    gradle user-microservice:assemble user-microservice:testClasses

checkStyle-authentication-microservice:
  stage: staticAnalysis
  script:
    gradle user-microservice:checkstyleMain user-microservice:checkStyleTest
  allow_failure: true

PMD-authentication-microservice:
  stage: staticAnalysis
  script:
    gradle user-microservice:pmdMain
  allow_failure: true

test-authentication-microservice:
  stage: test
  script:
    - gradle user-microservice:test user-microservice:jacocoTestReport
    - cat user-microservice/build/reports/test/test/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
